---
- hosts: all
  gather_facts: false
  vars:
    scanboxie_barcodemap_file_path: "/var/lib/mpd/music/Musik/BarcodeActions.yml"
  tasks:
  # MPD AND MPC SETUP
  - name: "install mpd (music player deamon) and mpc (music player client)"
    tags: ["mpd"]
    become: true
    ansible.builtin.package:
      name:
        - mpd
        - mpc
      state: latest

  - name: "copy mpd config"
    tags: ["mpd"]
    become: true 
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/files/mpd.conf"
      dest: /etc/mpd.conf

  - name: restart mpd service"
    tags: ["mpd"]
    become: true
    ansible.builtin.systemd:
      state: restarted
      name: mpd

  # SCANBOXIE SETUP

  - name: "copy scanboxie binary"
    tags: ["copy-scanboxie-binary"]
    become: true 
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/../scanboxie-arm"
      dest: /usr/bin/scanboxie
      mode: 0555
    notify: "restart scanboxie service"

  - name: "copy scanboxie config"
    become: true 
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/files/scanboxie.yml"
      dest: /etc/scanboxie.yml
    notify: "restart scanboxie service"

  - name: "copy scanboxie systemd unit file"
    become: true 
    ansible.builtin.template:
      src: "{{ playbook_dir }}/files/scanboxie.service.j2"
      dest: "/etc/systemd/system/scanboxie.service"
    notify: "restart scanboxie service"

  - name: "enable systemd scanboxie service"
    become: true
    ansible.builtin.systemd:
      state: started
      enabled: true
      daemon_reload: yes
      name: scanboxie
    notify: "restart scanboxie service"

  handlers:
  - name: "restart scanboxie service"
    become: true
    ansible.builtin.systemd:
      name: scanboxie
      state: restarted
  
